services:
  # 1. The Dashboard (Free Web Service)
  - type: web
    name: bot-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      # We will set RENDER_API_KEY and BOT_WORKER_SERVICE_ID manually
      # in the Render dashboard after the first deployment.
      - key: RENDER_API_KEY
        value: "" # Leave this blank for now
      - key: BOT_WORKER_SERVICE_ID
        value: "" # Leave this blank for now

  # 2. The Bot Runner (Free Background Worker - runs 24/7)
  - type: worker
    name: my-bot-runner
    env: python
    startCommand: "python bot_runner.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      # YOU WILL SET THIS in the Render dashboard to choose a bot
      - key: BOT_TO_RUN
        value: "client_a" # Default to running client_a's bot
