services:
  # Service 1: The Dashboard (uses your Free Web Service)
  - type: web
    name: bot-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      # IMPORTANT: We will set these two keys MANUALLY in the Render
      # Dashboard after the first deployment.
      - key: RENDER_API_KEY
        value: "" # Leave this blank for now
      - key: BOT_WORKER_SERVICE_ID
        value: "" # Leave this blank for now

  # Service 2: The Bot Runner (uses your Free Background Worker)
  - type: worker
    name: my-bot-runner
    env: python
    startCommand: "python bot_runner.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      # This tells the worker WHICH bot to run from your /bots/ folder.
      # Change this value in the Render Dashboard to switch bots.
      - key: BOT_TO_RUN
        value: "client_a"
